trigger:
  branches:
    include:
      - main  
      - release/*
  paths:
    include:
      - 'fabric_items/**'  

pool:
  vmImage: 'ubuntu-latest'  

parameters:
  - name: environment
    displayName: Deployment Environment
    type: string
    default: 'DEV'
    values:
      - 'DEV'
      - 'QA'
      - 'PROD'

variables:
  - name: targetEnvironment
    value: ${{ parameters.environment }}

stages:
- stage: DeployFabricItems
  displayName: 'Deploy Fabric Items'
  jobs:
  - job: AuthenticateAndDeploy
    displayName: 'Authenticate and Deploy'
    steps:
    - checkout: self  
      fetchDepth: 1   

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9' 
        addToPath: true
      displayName: 'Set up Python'

    - task: AzureKeyVault@2
      condition: or(eq(variables['targetEnvironment'], 'DEV'), eq(variables['targetEnvironment'], 'QA'))
      inputs:
        azureSubscription: 'fabric-sc'  
        KeyVaultName: '$(KeyVaultNameNonProd)'  
        SecretsFilter: 'tenant-id-secret, fabric-non-prod-secret, fabric-non-prod-spn-client-secret'
      displayName: 'Get Key Vault Secrets (DEV/QA)'

    - task: AzureKeyVault@2
      condition: eq(variables['targetEnvironment'], 'PROD')
      inputs:
        azureSubscription: 'fabric-sc-prod'  
        KeyVaultName: '$(KeyVaultNameProd)'  
        SecretsFilter: 'tenantID, fabric-prod-secret, fabric-prod-spn-client-secret'
      displayName: 'Get Key Vault Secrets (PROD)'

    - script: |
        python -m pip install --upgrade pip
        pip install -r .cicd/requirements.txt
      displayName: 'Install dependencies'


    - script: |
        echo "Target Environment: $(targetEnvironment)"
        ls -a
        python ./.cicd/authenticate_spn.py $(targetEnvironment)
      workingDirectory: $(Build.SourcesDirectory)/
      env:
        AZURE_CLIENT_ID: ${{ if eq(parameters.environment, 'PROD') }}:$(prod-spn-client-id)${{ else }}:$(fuam-spn-client-id)
        AZURE_TENANT_ID: ${{ if eq(parameters.environment, 'PROD') }}:$(prod-spn-tenant-id)${{ else }}:$(fuam-spn-tenant-id)
        AZURE_CLIENT_SECRET: ${{ if eq(parameters.environment, 'PROD') }}:$(prod-spn-secret)${{ else }}:$(fuam-spn-secret)
      displayName: 'Run authentication and deployment script'



