trigger:
  branches:
    include:
      - main  # Trigger on changes to the main branch
  paths:
    include:
      - 'fabric_items/**'  # Trigger on changes to files in the fabric_items directory

pool:
  vmImage: 'ubuntu-latest'  # Use the latest Ubuntu agent

parameters:
  - name: environment
    displayName: Deployment Environment
    type: string
    default: 'DEV'
    values:
      - 'DEV'
      - 'QA'
      - 'PROD'

variables:
  - name: targetEnvironment
    value: ${{ parameters.environment }}

stages:
- stage: DeployFabricItems
  displayName: 'Deploy Fabric Items'
  jobs:
  - job: AuthenticateAndDeploy
    displayName: 'Authenticate and Deploy'
    steps:
    - checkout: self  # Checkout the repository
      fetchDepth: 1   # Fetch only the latest commit

    - task: UsePythonVersion@0
      inputs:
        versionSpec: '3.9'  # Use Python 3.9
        addToPath: true
      displayName: 'Set up Python'

    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'fabric-sc'  # Name of the Azure service connection
        KeyVaultName: '$(KeyVaultName)'  # Value will be set in the pipeline variable
        SecretsFilter: '$(SecretName)'  # Secret name as specified in spn_config.yml
      displayName: 'Get Key Vault Secrets'

    - script: |
        python -m pip install --upgrade pip
        pip install -r .cicd/requirements.txt
      displayName: 'Install dependencies'    - script: |
        echo "Target Environment: $(targetEnvironment)"
        echo "Current Working Directory:"
        ls -la
        # Copy config files to the expected locations with Linux-compatible paths
        mkdir -p .cicd
        cp -f .cicd/spn_config.yml .cicd/spn_config.yml
        cp -f .cicd/target_deployment.yml .cicd/target_deployment.yml
        # Run the updated script
        python ./.cicd/authenticate_spn_platform_independent.py $(targetEnvironment)
      env:
        AZURE_CLIENT_ID: $(client-id)
        AZURE_TENANT_ID: $(tenant-id)
        AZURE_CLIENT_SECRET: $(spn-secret)
        # Set environment variables in case our script still needs them
        TARGET_ENV: $(targetEnvironment)
      displayName: 'Run authentication and deployment script'




# - task: AzureKeyVault@2
#   inputs:
#     azureSubscription: 'fabric-sc'
#     KeyVaultName: 'kvfabricprodeus2rh'
#     SecretsFilter: 'spn-secret'
#     RunAsPreJob: true
